// User related
export const USER_NOT_FOUND = "USER_NOT_FOUND";
export const USER_ALREADY_EXIST = "USER_ALREADY_EXIST";
export const USER_NEED_MIGRATE = "USER_NEED_MIGRATE";
export const USER_DISCORD_MIGRATE = "USER_LEGACY_DISCORD_AUTH";
export const USER_APPROVAL_INCORRECT = "USER_APPROVAL_INCORRECT";
export const USER_INVALID_PASSWORD = "USER_INVALID_PASSWORD";
export const USER_REQUIREMENT_PASSWORD = "USER_REQUIREMENT_PASSWORD";
export const USER_REQUIREMENT_USERNAME = "USER_REQUIREMENT_USERNAME";
export const USER_INVALID_OLD_PASSWORD = "USER_INVALID_OLD_PASSWORD";
export const USER_REPEAT_OLD_PASSWORD = "USER_REPEAT_OLD_PASSWORD";

// Session
export const SESSION_EXIST = "SESSION_EXIST";
export const SESSION_UNKNOWN = "SESSION_UNKNOWN";
export const SESSION_NOT_MASTER = "SESSION_NOT_MASTER";
export const SESSION_NOT_ALLOWED = "SESSION_NOT_ALLOWED";

// External Sources
export const ANILIST_API_ERROR = "ANILIST_API_ERROR";
export const ANILIST_API_UNAVAILABLE = "ANILIST_API_UNAVAILABLE";
export const TMDB_API_UNAVAILABLE = "TMDB_API_UNAVAILABLE";
export const TMDB_API_ERROR = "TMDB_API_ERROR";

// Servers
export const SERVER_UNSELECT = "SERVER_UNSELECT";
export const SERVER_NOT_FOUND = "SERVER_NOT_FOUND";
export const SERVER_NOT_ALLOWED = "SERVER_NOT_ALLOWED";
export const SERVER_ERROR = "SERVER_ERROR";
export const SERVER_ADD_MISSING_NAME = "SERVER_ADD_MISSING_NAME";

// Project
export const PROJECT_NOT_FOUND = "PROJECT_NOT_FOUND";
export const PROJECT_ADD_MISSING_EXTERNAL = "PROJECT_ADD_MISSING_EXTERNAL";
export const PROJECT_ADD_UNSUPPORTED_EXTERNAL = "PROJECT_ADD_UNSUPPORTED_EXTERNAL";
export const PROJECT_ADD_START_TIME_UNKNOWN = "PROJECT_ADD_START_TIME_UNKNOWN";
export const PROJECT_UPDATE_NO_EPISODE = "PROJECT_UPDATE_NO_EPISODE";

// Other
export const SUCCESS = "SUCCESS";
export const NOT_IMPLEMENTED = "NOT_IMPLEMENTED";
export const IMAGE_UPLOAD_FAILED = "IMAGE_UPLOAD_FAILED";
